runtime: python
env: flex # for Google Cloud Flexible App Engine
entrypoint: gunicorn -b :$PORT mysite.wsgi # specific to a GUnicorn HTTP server deployment
service: hackweeksearch

manual_scaling:
  instances: 1

resources:
  cpu: 4
  memory_gb: 8
  disk_size_gb: 30

runtime_config:
  python_version: 3

#env_variables:
#  GLEAN_LOG_PINGS: true
#  GLEAN_DEBUG_VIEW_TAG: "mlhackweek-search"
